---
src_vocab: '/mnt/lustre/xushuang1/zy/zhyang/dl4mt/corpus/data_gan_180w_zxw/180w_bpe_lf_50_for_generate_data/source_bpe_u8.txt.vocab.38831'
dst_vocab: '/mnt/lustre/xushuang1/zy/zhyang/dl4mt/corpus/data_gan_180w_zxw/180w_bpe_lf_50_for_generate_data/target_bpe_u8.txt.vocab.34432'
src_vocab_size: 38831
dst_vocab_size: 34432
hidden_units: 512
scale_embedding: True
attention_dropout_rate: 0.0
residual_dropout_rate: 0.1
num_blocks: 6
num_heads: 8
binding_embedding: False
train:
    devices: '0,1,2,3,4,5,6,7'
    src_path: '/mnt/lustre/xushuang1/zy/zhyang/dl4mt/corpus/data_gan_180w_zxw/180w_bpe_lf_50_for_generate_data/source_bpe_u8.txt_lf_50'
    out_path: '/mnt/lustre/xushuang1/zy/zhyang/dl4mt/corpus/data_gan_180w_zxw/180w_bpe_lf_50_for_generate_data/negative_bpe_u8.txt'
    tokens_per_batch:  25000
    max_length: 50
    num_epochs: 1
    logdir: '../experience/data_180w/generate_data/model-180w_zh2en_bpe'
    save_freq: 1000
    summary_freq: 100
    grads_clip: 5.0
    optimizer: 'adam_decay'
    learning_rate: 0.00005
    learning_rate_warmup_steps: 4000
    label_smoothing: 0.1
    batch_size: 256
    shared_embedding: False
    modelFile: '../experience/data_180w/generate_data/model-180w_zh2en_bpe/model_epoch_10_step_42000'
